// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Wrong Usage", "DF0010:Marks undisposed local variables.", Justification = "Code generated by Visual Studio", Scope = "type", Target = "~T:Multiverse.WebApp.Services.ApiClient")]
[assembly: SuppressMessage("Wrong Usage", "DF0032:Marks undisposed objects assinged to a property, originated in an object creation.", Justification = "Code generated by Visual Studio", Scope = "type", Target = "~T:Multiverse.WebApp.Services.ApiClient")]
